#!/bin/bash
if [ ! -d ".git" ]; then
    echo "No .git directory, skipping pre-commit installation."
    exit 1
fi
if [ ! -f ".pre-commit-config.yaml" ]; then
    echo "No pre-commit configuration file found, skipping pre-commit installation."
    exit 1
fi

OS=$(uname)

if [[ "$OS" == "Darwin" ]]; then
  if command -v brew &>/dev/null; then
    brew install pre-commit
  else
    pip install pre-commit
  fi
elif [[ "$OS" == "Linux" ]]; then
  if command -v brew &>/dev/null; then
    brew install pre-commit
  else
    pip install pre-commit
  fi
elif [[ "$OS" == "MINGW"* ]] || [[ "$OS" == "MSYS"* ]]; then
  if command -v choco &>/dev/null; then
    choco install pre-commit
  else
    pip install pre-commit
  fi
else
    echo "Unsupported operating system"
    exit 1
fi


pre-commit install