replicaCount: 1
image:
  repository: doganince/core-api
  pullPolicy: IfNotPresent
  tag: 'v1.0.5'
imageCredentials:
  name: dockerhubcredentials
  registry: https://index.docker.io/v1/
#   username: to-be-pass # pragma: allowlist-secret
#   password: to-be-pass # pragma: allowlist-secret
# imagePullSecrets:
#   - name: dockerhubcredentials
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: ''
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: core-api.domain.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "500m"
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
