name: Create Release

on:
  release:
    types: [published]

jobs:
  run-tests-and-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies - CoreAPI
        run: dotnet restore ./src/apps/core-api
      - name: Build project - CoreAPI
        run: dotnet build ./src/apps/core-api/CoreAPI.csproj --no-restore
      - name: Run tests - CoreAPI
        run: dotnet test ./src/apps/core-api/CoreAPI.csproj --no-build --verbosity normal

  publish-to-artifactory:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image - CoreAPI
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/apps/core-api/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY_NAMESPACE }}/core-api:${{ github.event.release.tag_name }}