name: Run Tests

on:
  workflow_dispatch:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint started
        run: echo "::warning::job not implemented yet"
        
  run-tests:
    runs-on: ubuntu-latest
    needs: run-lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies - CoreAPI
        run: dotnet restore ./src/apps/core-api
      - name: Build project - CoreAPI
        run: dotnet build ./src/apps/core-api/CoreAPI.csproj --no-restore
      - name: Run tests - CoreAPI
        run: dotnet test ./src/apps/core-api/CoreAPI.csproj --no-build --verbosity normal