name: Multi Workflow Dispatcher

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: tests running
        run: echo "Triggering Workflow 1"

  bump-version:
    if: ${{ github.event.inputs.environment == 'production' || github.event.inputs.environment == 'staging' }}
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: tests running
        run: echo "Triggering Workflow 1"

  run-lint:
    if: ${{ github.event.inputs.environment == 'production' || github.event.inputs.environment == 'staging' }}
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: tests running
        run: echo "Triggering Workflow 1"
       
  run-release:
    if: ${{ github.event.inputs.environment != 'development' }}
    needs: [run-tests, run-lint]
    runs-on: ubuntu-latest
    steps:
      - name: release creating
        run: echo "Triggering Workflow 2"
       
  # run-publish artifactory:
  #   if: ${{ github.event.inputs.publishImage == 'true' }}
  #   needs: [run-release, run-lint]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: publishing docker images
  #       run: echo "Triggering Workflow 3"
      