name: Multi Workflow Dispatcher

on:
  workflow_dispatch:
    inputs:
      runTest:
        description: "run tests"
        required: true
        type: boolean
        default: true
      createRelease:
        description: "create new release"
        required: true
        type: boolean
        default: true
      publishImage:
        description: "publish Docker Image"
        required: true
        type: boolean
        default: true
        
jobs:
  trigger-tests:
    if: ${{ github.event.inputs.runTest == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: tests running
        run: echo "Triggering Workflow 1"

  trigger-lint:
    if: ${{ github.event.inputs.runTest == 'true' }}
    needs: trigger-tests
    runs-on: ubuntu-latest
    steps:
      - name: tests running
        run: echo "Triggering Workflow 1"
       
  trigger-release:
    if: ${{ github.event.inputs.createRelease == 'true' }}
    needs: [trigger-tests, trigger-lint]
    runs-on: ubuntu-latest
    steps:
      - name: release creating
        run: echo "Triggering Workflow 2"
       
  trigger-workflow3:
    if: ${{ github.event.inputs.publishImage == 'true' }}
    needs: [trigger-release, trigger-lint]
    runs-on: ubuntu-latest
    steps:
      - name: publishing docker images
        run: echo "Triggering Workflow 3"
      