name: Multi Workflow Dispatcher

on:
  workflow_dispatch:
    inputs:
      runTest:
        description: "run tests?"
        required: true
        type: boolean
        default: true
      createRelease:
        description: "create new release?"
        required: true
        type: boolean
        default: true
      bumpVersion:
        description: "bump version?"
        required: true
        type: boolean
        default: true
      publishImage:
        description: "publish docker image?"
        required: true
        type: boolean
        default: true

jobs:
  run-tests:
    if: ${{ github.event.inputs.runTest == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: tests running
        run: echo "Triggering Workflow 1"

  bump-version:
    if: ${{ github.event.inputs.bumpVersion == 'true' }}
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: tests running
        run: echo "Triggering Workflow 1"

  run-lint:
    if: ${{ github.event.inputs.runTest == 'true' }}
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: tests running
        run: echo "Triggering Workflow 1"
       
  run-release:
    if: ${{ github.event.inputs.createRelease == 'true' && (github.event.inputs.bumpVersion == 'false' || needs.bump-version.result == 'success' ) }}
    needs: [run-tests, run-lint]
    runs-on: ubuntu-latest
    steps:
      - name: release creating
        run: echo "Triggering Workflow 2"
       
  # run-publish artifactory:
  #   if: ${{ github.event.inputs.publishImage == 'true' }}
  #   needs: [run-release, run-lint]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: publishing docker images
  #       run: echo "Triggering Workflow 3"
      