name: Multi Workflow Dispatcher

on:
  workflow_dispatch:
    inputs:
      run_workflow1:
        description: "Run Workflow 1?"
        required: true
        type: boolean
      run_workflow2:
        description: "Run Workflow 2?"
        required: true
        type: boolean

jobs:
  trigger-workflow1:
    if: ${{ github.event.inputs.run_workflow1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Log Trigger Workflow 1
        run: echo "Triggering Workflow 1"
       
  trigger-workflow2:
    if: ${{ github.event.inputs.run_workflow2 == 'true' }}
    needs: trigger-workflow1
    runs-on: ubuntu-latest
    steps:
      - name: Log Trigger Workflow 2
        run: echo "Triggering Workflow 2"
       
  trigger-workflow3:
    if: ${{ github.event.inputs.run_workflow1 == 'true' || needs.trigger-workflow2.result == 'skipped'}}
    needs: [trigger-workflow1, trigger-workflow2]
    runs-on: ubuntu-latest
    steps:
      - name: Log Trigger Workflow 3
        run: echo "Triggering Workflow 3"
       