name: Multi Workflow Dispatcher

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: tests started
        run: echo "job started with name:run test"
      - name: tests completed
        run: echo "job completed with name:run test"

  bump-version:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: tests started
        run: echo "job started with name:bump-version"
      - name: tests completed
        run: echo "job started with name:bump-completed"

  run-lint:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: tests started
        run: echo "job started with name:run-lint"
      - name: tests completed
        run: echo "job completed with name:run-lint"
       
  run-release:
    needs: run-lint
    runs-on: ubuntu-latest
    steps:
      - name: tests started
        run: echo "job started with name:run-release"
      - name: tests completed
        run: echo "job completed with name:run-release"